#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025-2026 Qodeca sp. z o.o.
# SPDX-License-Identifier: GPL-3.0-only
# gate-18-skill-registry.sh — keeps docs/skill-registry.md honest about the
# skills this plugin ships.
#
# The registry is generated by scripts/gen-skill-registry.sh from `ls skills/`
# plus `git log -1` per skill directory. This gate does NOT whole-file diff
# against a fresh generation, because dates go stale by construction: the
# commit that changes a skill is itself the commit that invalidates the row,
# and squash-merging collapses any follow-up refresh commit back into the same
# problem. A gate that failed on that would red-light `develop` after every
# skill change without catching anything a reader would be misled by.
#
# Instead it splits the checks by what actually misleads:
#
#   HARD  0. The repository is not a shallow clone (every row would be garbage).
#   HARD  1. The registry exists, its table parses, and no skill is listed twice.
#   HARD  2. Its skill list equals `ls skills/` minus design-shared — catches a
#            skill added, removed, or renamed without regenerating.
#   HARD  3. No row claims something git cannot account for: a date ahead of
#            history, or - on a row whose date git confirms - a commit subject
#            that is not that commit's subject. Catches hand-edited tables.
#   WARN  4. Rows behind git are reported with the fix command. Expected between
#            releases; the release process regenerates (see CLAUDE.md).
#
# The subject-rendering rule (truncate to 72 chars, then escape pipes) is
# MIRRORED from gen-skill-registry.sh. Change one, change both.
#
# Run standalone:  bash scripts/gate-18-skill-registry.sh
set -euo pipefail
cd "$(dirname "$0")/.."

python3 <<'PYEOF'
import os
import re
import subprocess
import sys
from glob import glob

TARGET = 'docs/skill-registry.md'
FIX = 'bash scripts/gen-skill-registry.sh'
errors, warnings, passes = [], [], []

# --- Check 0: shallow clone (hard) ------------------------------------------
# `git log -1 -- <path>` in a shallow clone reports the grafted tip commit for
# EVERY path, so both this gate and the generator would agree on garbage.
if subprocess.run(['git', 'rev-parse', '--is-shallow-repository'],
                  capture_output=True, text=True).stdout.strip() == 'true':
    print('  FAIL: shallow clone — every skill would resolve to the tip commit. '
          'Deepen first: git fetch --unshallow')
    sys.exit(1)

# --- filesystem + git truth -------------------------------------------------
fs_skills = sorted(
    os.path.basename(os.path.normpath(d))
    for d in glob('skills/*/')
    if os.path.basename(os.path.normpath(d)) != 'design-shared'
)


def git_log(fmt, skill, extra=()):
    out = subprocess.run(
        ['git', 'log', '-1', f'--format={fmt}', *extra, '--', f'skills/{skill}/'],
        capture_output=True, text=True,
    )
    return out.stdout.strip()


def render_subject(subject):
    """MIRRORED from gen-skill-registry.sh - truncate first, escape second."""
    if len(subject) > 72:
        subject = subject[:69] + '...'
    return subject.replace('|', r'\|')


if not os.path.isfile(TARGET):
    print(f'  FAIL: {TARGET} is missing. Run: {FIX}')
    sys.exit(1)

# --- Check 1: the table parses, no duplicate rows (hard) --------------------
# Skill cell is [^|]+ rather than [a-z0-9-]+ on purpose: an odd directory name
# should surface as a skill-list mismatch with an actionable message, not as an
# unparseable row the fix command cannot clear.
ROW = re.compile(r'^\|\s*([^|]+?)\s*\|\s*(\d{4}-\d{2}-\d{2}|uncommitted)\s*\|\s*(.*?)\s*\|\s*$')
registry, seen_lines = {}, {}
in_table = False
for i, line in enumerate(open(TARGET).read().split('\n'), start=1):
    if line.startswith('| Skill '):
        in_table = True
        continue
    if not in_table or not line.startswith('|') or line.startswith('|---'):
        continue
    m = ROW.match(line)
    if not m:
        errors.append(f'{TARGET}:{i}: table row does not parse: {line.strip()[:80]}')
        continue
    skill, date, subject = m.group(1), m.group(2), m.group(3)
    if skill in registry:
        errors.append(
            f'{TARGET}:{i}: `{skill}` listed twice (first at line {seen_lines[skill]}) — '
            f'regenerate with: {FIX}'
        )
        continue
    registry[skill] = (date, subject)
    seen_lines[skill] = i

if not registry and not errors:
    errors.append(f'{TARGET}: no skill rows found — the table is missing or malformed')

# --- Check 2: skill list matches the filesystem (hard) ----------------------
missing = [s for s in fs_skills if s not in registry]
extra = [s for s in registry if s not in fs_skills]
if missing:
    errors.append(f'{TARGET}: skill(s) missing from the registry: {", ".join(missing)} — run: {FIX}')
if extra:
    errors.append(f'{TARGET}: registry lists skill(s) that no longer exist: {", ".join(extra)} — run: {FIX}')
if registry and not missing and not extra:
    passes.append(f'registry lists exactly the {len(fs_skills)} shipped skill(s)')

# --- Checks 3 + 4: rows against git -----------------------------------------
stale, row_errors = [], 0
for skill in fs_skills:
    if skill not in registry:
        continue
    claimed_date, claimed_subject = registry[skill]
    actual_date = git_log('%ad', skill, ('--date=short',)) or 'uncommitted'
    actual_subject = render_subject(git_log('%s', skill) or 'not yet committed')

    if actual_date == 'uncommitted':
        # git knows nothing about this directory yet. A row claiming a real
        # date is asserting history that does not exist.
        if claimed_date != 'uncommitted':
            row_errors += 1
            errors.append(
                f'{TARGET}: `{skill}` claims {claimed_date} but git has no commit for it — '
                f'a registry date cannot precede history (hand-edited?)'
            )
        continue

    if claimed_date == 'uncommitted':
        # Ordinary lag: the registry was generated before the skill was
        # committed. Warn - this is the documented add-a-skill workflow.
        stale.append(f'{skill}: registry uncommitted, git {actual_date}')
    elif claimed_date > actual_date:
        row_errors += 1
        errors.append(
            f'{TARGET}: `{skill}` claims {claimed_date} but git says {actual_date} — '
            f'a registry date cannot be newer than history (hand-edited?)'
        )
    elif claimed_date < actual_date:
        stale.append(f'{skill}: registry {claimed_date}, git {actual_date}')
    elif claimed_subject != actual_subject:
        # Date matches, so git pins the exact commit - the subject is knowable
        # and wrong. Not staleness; someone edited the cell.
        row_errors += 1
        errors.append(
            f'{TARGET}: `{skill}` row for {claimed_date} says "{claimed_subject}" but that '
            f'commit\'s subject is "{actual_subject}" (hand-edited?)'
        )

if registry and not stale and not row_errors:
    passes.append('every registry row matches git history')
if stale:
    warnings.append(f'{len(stale)} row(s) behind git — regenerate with: {FIX}')
    warnings.extend(f'  {s}' for s in stale)

# --- output -----------------------------------------------------------------
for p in passes:
    print(f'  PASS: {p}')
for w in warnings:
    print(f'  WARN: {w}')
for e in errors:
    print(f'  FAIL: {e}')
sys.exit(1 if errors else 0)
PYEOF
